
run:
	# /appl/python/3.8.17/bin/python3 -m tools.visualization --opt_path checkpoints/t2m/t2m_motiondiffuse/opt.txt --text "a man sits"
	python3 -m tools.visualization --opt_path checkpoints/t2m/t2m_motiondiffuse/opt.txt --text "a man sits"